<a href="https://colab.research.google.com/github/Usha-Chandana/FMML-Lab/blob/main/Basics_of_Python_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 0

In [1]:
# string methods

#count
txt ="Apple Apple Mango Apple"
x = txt.count("Apple")
print(x)

#split

txt = "My name is Usha Chandana"
x = txt.split(" ")
print(x)

#replace
x = txt.replace("Chandana", "M")
print(x)

3
['My', 'name', 'is', 'Usha', 'Chandana']
My name is Usha M


In [2]:
#List methods

#append
subjects = ['DBMS', 'ML' , 'AI']
subjects.append("LAC")
print(subjects)

#insert
subjects.insert(2, "OS")
print(subjects)

#reverse
subjects.reverse()
print(subjects)

['DBMS', 'ML', 'AI', 'LAC']
['DBMS', 'ML', 'OS', 'AI', 'LAC']
['LAC', 'AI', 'OS', 'ML', 'DBMS']


In [10]:
#Tuple methods

#count
tuple1 = (1, 3, 5, 8, 2, 6, 3, 3, 0, 3)

print(tuple1.count(3))

#index

print(tuple1.index(8))

4
3


In [11]:
#Set methods

#add

first = {"A", "B", "C"}
first.add("D")
print(first)

#copy

second = first.copy()
print(second)
second.add("E")

#difference

third = second.difference(first)
print(third)

{'A', 'C', 'B', 'D'}
{'A', 'C', 'B', 'D'}
{'E'}


In [12]:
#dictionary methods

#get

subjects = {
  1: "one",
  2: "two",
  3: "three"
}

print(subjects.get(2))

#values

print(subjects.values())

#items

print(subjects.items())

two
dict_values(['one', 'two', 'three'])
dict_items([(1, 'one'), (2, 'two'), (3, 'three')])


Question 1

In [14]:
def function(a,b):
  str=a[::-1]
  str=str+b
  return str

x=function("abcd","efgh")
print(x)

dcbaefgh


Question 2

In [18]:
details = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
max=0

for i in details:
  for j in i:
    if(j=='F' and max<=i[1]):
      max=i[1]
      name=i[0]
print(name)
print(max*20)

Penny
18400


Question 3(a)

In [38]:
import numpy as np

a=np.arange(1,6)
x=np.vstack((a,a,a,a,a))
res=x.T
res

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5]])

Question 3(b)

In [39]:
b=np.arange(0,25).reshape(5,5)
print(b)
res@b


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 50,  55,  60,  65,  70],
       [100, 110, 120, 130, 140],
       [150, 165, 180, 195, 210],
       [200, 220, 240, 260, 280],
       [250, 275, 300, 325, 350]])